#!/bin/bash


if [ ! -d /run/sshd ];then 

	mkdir -p /run/sshd

fi


if [ "$SSHPORT" != "" ];then

	echo "Port $SSHPORT" >> /etc/ssh/sshd_config

fi



chmod +x /opt/nstools/bin/*
exec /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config